# Generated by Django 2.2.16 on 2022-02-16 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='rating',
        ),
        migrations.AlterField(
            model_name='title',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('author', 'title')},
        ),
    ]
