# Generated by Django 2.2.16 on 2022-02-16 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdb', '0004_auto_20220216_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='password', max_length=128),
        ),
    ]
