# Generated by Django 2.2.16 on 2022-02-19 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdb', '0005_auto_20220216_2247'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='confirmation_code',
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('author', 'title'), name='unique.review'),
        ),
    ]
