# Generated by Django 2.2.16 on 2022-02-19 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdb', '0006_auto_20220219_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='0000', max_length=4),
        ),
    ]
